apiVersion: v1
kind: Service
metadata:
  name: telegram-whatsapp-bot
spec:
  type: combined
  framework: dockerfile
  dockerfile:
    buildEngine: kaniko
    dockerfilePath: Dockerfile
    dockerContext: .
  deployment:
    instances: 1
    storage:
      persistentStorage:
        - name: whatsapp-session
          path: /app/whatsapp-session
          size: 1024
        - name: logs
          path: /app/logs
          size: 512
  resources:
    cpu: 0.5
    memory: 1024
  runtimeEnvironment:
    - name: NODE_ENV
      value: production
    - name: DATABASE_URL
      secretKeyRef:
        name: database-credentials
        key: url
    - name: TELEGRAM_BOT_TOKEN
      secretKeyRef:
        name: telegram-credentials
        key: token
    - name: ADMIN_USER_ID
      secretKeyRef:
        name: admin-credentials
        key: user_id
    - name: PORT
      value: "3000"
  ports:
    - name: http
      internalPort: 3000
      public: false
