apiVersion: v1
kind: Service
metadata:
  name: telegram-whatsapp-bot
spec:
  type: combined
  framework: dockerfile
  dockerfile:
    buildEngine: kaniko
    dockerfilePath: /Dockerfile
    dockerContext: /
  deployment:
    instances: 1
    storage:
      ephemeralStorage: 2048
      persistentStorage:
        - name: whatsapp-session
          path: /app/whatsapp-session
          size: 1024
        - name: logs
          path: /app/logs
          size: 512
  scaling:
    horizontalPolicy:
      maxReplicas: 1
      minReplicas: 1
  resources:
    cpu: 0.5
    memory: 1024
  runtimeEnvironment:
    - name: NODE_ENV
      value: production
    - name: DATABASE_URL
      secretKeyRef:
        name: database-credentials
        key: url
    - name: TELEGRAM_BOT_TOKEN
      secretKeyRef:
        name: telegram-credentials
        key: token
    - name: ADMIN_USER_ID
      secretKeyRef:
        name: admin-credentials
        key: user_id
  healthChecks:
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
  ports:
    - name: http
      internalPort: 3000
      public: false
